### ISSUE TITLE
Solita doesnt seem to work on anchor v0.28.0

### ISSUE THREAD

**Issue by tanmaymunjal** [metaplex-foundation/solita#107]
Solita doesn't seem to work on the latest anchor version 0.28.0 due to a lack of anchor-cli 0.28.0 support rn. Is there anything we can do to solve this issue on our end? Or is the only recourse to wait to anchor-cli v0.28.0 to be released?

![image](https://github.com/metaplex-foundation/solita/assets/72982935/5034d50f-b56f-4755-bd7f-76ba24572342)

**Comment by tanmaymunjal** [comment]
Anchor cli 0.28.0 seems to be releases, so closing this here

**Comment by tanmaymunjal** [comment]
Closing this here as it seems to be an AVM issue rather than no anchor cli v0.28.0 being released

**Comment by Swertin** [comment]
@tanmaymunjal What was your solution? Tried everything, from building my own anchor bin, ripping out avm, housing a .cargo directory with the anchor binary directly in my SDK folder, etc...
