### ISSUE TITLE
[feat] Support UnixTimestamp

### ISSUE THREAD

**Issue by blockiosaurus** [metaplex-foundation/solita#45]
Add support to Solita/beet for UnixTimestamp. An alias to i64 should work since that's all the UnixTimestamp type is. Attached is the Auctioneer IDL which fails due to this.
[auctioneer.txt](https://github.com/metaplex-foundation/solita/files/8645647/auctioneer.txt)

**Comment by thlorenz** [comment]
Thanks I'll have a look!

**Comment by blockiosaurus** [comment]
Here's the Rust code that uses UnixTimestamp https://github.com/blockiosaurus/metaplex-program-library/blob/ah_add_auctioneer/auctioneer/program/src/sell/config.rs

**Comment by thlorenz** [comment]
So the only reference for a `unix_timestamp` I find [in this library](https://docs.rs/unix-timestamp/latest/unix_timestamp/fn.unix_timestamp.html).

Could you link me to the actual Rust type and/or provide a link to the Rust program that uses this type?

**Comment by thlorenz** [comment]
Ah ok thanks for the link :)

**Comment by thlorenz** [comment]
So this isn't even a built in Rust type you're using .. it's a Solana type.
Gonna have to see how to best handle those cases.

**Comment by thlorenz** [comment]
Was able to confirm now that this is a synonym for `u64` see [here](https://docs.rs/solana-program/latest/solana_program/clock/type.UnixTimestamp.html)

**Comment by thlorenz** [comment]
I may need to come up with a more generic solution for these cases as I cannot add each alias to solita whenever we run into one.
Most likely it is better to allow to configure those instead.
