### ISSUE TITLE
generated sdk doesnt have types

### ISSUE THREAD

**Issue by anoushk1234** [metaplex-foundation/solita#51]
Is there anyway i can generate types for the sdk too?
```
Could not find a declaration file for module 'metapass-sdk'. '/Users/anoushkkharangate/Documents/mpsolv2/metapass-solana/node_modules/metapass-sdk/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/metapass-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'metapass-sdk';`ts(7016)
  ```
  <img width="1119" alt="Screenshot 2022-05-20 at 4 23 45 PM" src="https://user-images.githubusercontent.com/32778608/169513341-e763de22-52a4-4211-b4d0-c6fe4264f632.png">

**Comment by SkullTech** [comment]
@anoushk1234 look into declarations

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
https://www.typescriptlang.org/tsconfig#declaration

**Comment by anoushk1234** [comment]
Hey @SkullTech that worked thanks!
