### ISSUE TITLE
[feat]:support BTreeMap

### ISSUE THREAD

**Issue by imoyakin** [metaplex-foundation/solita#69]
```bash
AssertionError [ERR_ASSERTION]: Unknown type BTreeMap<u32,u32> is neither found in types nor an Account
```

support BTreeMap generate for program, like `nft-packs`

**Comment by thlorenz** [comment]
This is an anchor issue actually since it adds types that it doesn't understand as `defined` types.
Please see more in #76 which should also fix your issue.
Therefore please upgrade to latest solita and try again please and LMK if we can close or if something else is needed.

**Comment by imoyakin** [comment]
thanks for you work!
Now  program Internal definitions do not affect code generation.
