### ISSUE TITLE
[feat]: Support for non-uniform Data Enums

### ISSUE THREAD

**Issue by ngundotra** [metaplex-foundation/solita#71]
Right now, Solita is unable to handle IDL types that have the following structure:

```json    
  {
      "name": "VoteThreshold",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "YesVotePercentage",
            "fields": [
              "u8"
            ]
          },
          {
            "name": "QuorumPercentage",
            "fields": [
              "u8"
            ]
          },
          {
            "name": "Disabled"
          }
        ]
      }
    }
```
Would be helpful for automatically maintaining SDKs like for SPL Governance.

**Comment by ngundotra** [comment]
Even Anchor doesn't have support for this: https://github.com/coral-xyz/anchor/blob/698426033052781988cd7980249726501ae08bdc/ts/src/coder/borsh/idl.ts#L126-L142

**Comment by thlorenz** [comment]
Could you have another go as I think https://github.com/metaplex-foundation/solita/pull/72 might have fixed this as well.
This now handles mixed enums i.e. with data and scalar variants.

**Comment by ngundotra** [comment]
Yes this is done! Thank you Thorsten :)
