### ISSUE TITLE
Exceptional case where the IDL type definition is not met

### ISSUE THREAD

**Issue by ricardocr987** [metaplex-foundation/solita#78]
I have encountered a bug, trying to use solita for the Jupiter and Jet Protocol programs:

The bug is as follows:
<img width="936" alt="Screenshot 2022-08-29 at 10 48 24" src="https://user-images.githubusercontent.com/32191898/187162357-bf4f599e-ef0a-451d-89de-0935a4a951a8.png">

When I try to display the requireds variable of the renderIxAccountKeys function of render-instructions I get this: 
<img width="194" alt="Screenshot 2022-08-29 at 09 52 22" src="https://user-images.githubusercontent.com/32191898/187159462-1b1717d4-3f5b-4521-b7ab-74873b6e44b3.png">

Looking at the Jet code (which is open source), I noticed this:
- https://github.com/jet-lab/jet-v1/blob/master/programs/jet/src/instructions/liquidate_dex.rs#L759

This is the context of the instruction that cause the problem on Jet, seems like they created different custom collections of accounts to reuse that definition on the same instruction (source_market, target_market):
- https://github.com/jet-lab/jet-v1/blob/master/programs/jet/src/instructions/liquidate_dex.rs#L35
- https://github.com/jet-lab/jet-v1/blob/master/programs/jet/src/instructions/liquidate_dex.rs#L186

This is the instruction causing the bug on the IDL: https://github.com/jet-lab/jet-v1/blob/master/app/public/idl/mainnet-beta/jet.json#L901 if you look inside the vector accounts of the instruction it has several vectors of accounts that do not comply with the type definition in solita, this is the case that gives problems that's why I get the Objects in the console

**Comment by thlorenz** [comment]
Thanks for reporting.
From a quick look it seems that the IDL incorrectly nests accounts for the `mockLiquidateDex` instruction.
It's first account `sourceMarket` has itself an accounts property which is currently not supported (and I'm not sure it makes no sense either).

A instruction should just have a list of accounts, each of type `AccountMetadata` (not arrays or anything else).

Therefore I think that the tool that generated the IDL might not support your setup properly.
