### ISSUE TITLE
feat: support statically positioned optional accounts

### ISSUE THREAD

**Issue by nilz3ro** [metaplex-foundation/solita#93]
Complex instructions may depend on multiple optional accounts, it's useful to default optional accounts to the program ID so that the account is still present even if a client doesn't pass in an optional account.
This makes it so that the program can still depend on the order of accounts, even when multiple optional accounts are not specified by the client.

It would be useful to have an attribute that we can use to tell Solita to fill in optional accounts with the program ID.

```rust
#[fill_optional]
#[account(1, signer, name = "payer", desc = "...")]
#[account(2, optional, writable, name = "token", desc = "...")]
#[account(3, optional, writable, name = "metadata", desc = "...")]
#[account(4, optional, writable, name = "edition", desc = "...")]
#[account(5, optional, writable, name = "collection")]
TransferIn,
```
Then, inside of the generated instruction builder functions, Solita can use the nullish coalescing operator `??` to default to the program's address.

```js
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.token ?? programId,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.metadata ?? programId,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.edition ?? programId,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection ?? programId,
      isWritable: true,
      isSigner: false,
    },
  ];
```

**Comment by thlorenz** [comment]
Fixed via https://github.com/metaplex-foundation/solita/pull/94
